#����˿�����
server:
  port: 8081


#���ݿ�����
spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/db_demo
     username: root
     password: 123456
#druid���ݿ����ӳ�(��������,�ٶ�һ��~)
     type: com.alibaba.druid.pool.DruidDataSource
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20

#mybatis����
mybatis:
   mapper-locations: classpath:mapping/*.xml
   type-aliases-package: com.cr.demo.model

#pagehelper��ҳ���
#pagehelper:
#helper-dialect: mysql
#reasonable: true
#support-methods-arguments: true
#params: count=countSql






